### ISSUE TITLE
Ingen transaksjoner vises

### ISSUE THREAD

**Issue by langtind** [Wedvich/sbanken-ynab#107]
Har sjekket ut siste versjon av sbanken-ynab (master) og satt den opp. I oversiktsfeltet øverst vises korrekt informasjon, men ingen transaksjoner vises i listen (hverken fra YNAB eller Sbanken, og uavhengig av om jeg velger "Kun bokførte" eller "Alle"). 

Får error i console som indikerer at det er problemer med formatet 🤷🏼
```
chunk-532WZUPY.js?v=d78b247f:784 TypeError: Cannot destructure property 'transactions' of 'data.data' as it is undefined.
    at Object.queryFn (ynab.api.ts:109:17)
(anonymous) @ chunk-532WZUPY.js?v=d78b247f:784
Show 1 more frame
Show less
chunk-532WZUPY.js?v=d78b247f:784 TypeError: Cannot destructure property 'payees' of 'data.data' as it is undefined.
    at Object.queryFn (ynab.api.ts:493:17)
``` 
Har fungert tidligere for meg, men er en stund siden sist jeg brukte sbanken-ynab. Jeg startet også akkurat med et nytt budsjett i YNAB, så lite / ingen data der.

![CleanShot 2024-01-04 at 15 47 15](https://github.com/Wedvich/sbanken-ynab/assets/90274/cf694935-5641-4e2f-8775-1b1672274963)

(Og tusen takk for et nydelig verktøy!! 🙌🏼)

**Comment by Wedvich** [comment]
Hey, først: beklager sent svar! Så rart at det ikke fungerer - så vidt jeg kan se har ikke YNAB gjort noen endringer på API'et sitt 🤔 Men ser det er mye warnings rundt MSW, så det er mulig det har klart å snike seg inn en "feil" service worker fra en tidligere versjon der? Du kan prøve disse stegene:

1. Gå til "Applications" og så "Storage" i devtools og pass på at "Unregister service workers" er huket av
2. Trykk "Clear site data"
3. Lukk alle fanene med sbanken-ynab
4. Åpne igjen og logg inn på nytt. Da må du sette opp konto-koblingene igjen, men det burde være fort gjort.

Kan du se om det funker først, så prøver vi videre derfra hvis ikke?

**Comment by langtind** [comment]
Yes! Det løste problemet. Nå fungerer det igjen som det skal! Tusen takk for hjelpen!
