### ISSUE TITLE
Feature Request: Mulighet for å synkronisere med to sbank brukere

### ISSUE THREAD

**Issue by hanfil** [Wedvich/sbanken-ynab#3]
Nå er det kun mulighet for å hente transaksjonsdata fra en sbank bruker.
Hadde det vært mulig å lage knapp for å tilknytte flere sbank brukere?
Å knytte en annen sbank brukers account til en account i ynab.

**Comment by Wedvich** [comment]
Det går nok an ja! Jeg er usikker på hvor mye arbeid det blir å matche opp transaksjoner på tvers av flere Sbanken-brukere, men jeg kan gjerne se på det.

Hva er use caset, så jeg forstår det litt bedre? Er dere flere personer som deler en YNAB-konto for å holde styr på fellesøkonomien?

**Comment by hanfil** [comment]
Ja det er meg og kona mi som har fellesøkonmi og vi deler en ynab konto, slik at begge har oversikt over hvor mye som er igjen.

Workaround jeg har funnet er at jeg bare bruker incognito eller forskjellige nettlesere for å synke opp med en annen sbank konto.

**Comment by Wedvich** [comment]
Skjønner, takk for beskrivelsen! Har lekt med tanken på å gjøre det mulig å legge til flere banker etter hvert, men samme fremgangsmåten burde kunne brukes til å legge inn flere Sbanken-brukere også. Skal se hva jeg får til! 😃
