### ISSUE TITLE
Får ikke opp ynab-kontoer når jeg har lagt inn api-nøkkel

### ISSUE THREAD

**Issue by metasikander** [Wedvich/sbanken-ynab#61]
Jeg får ikke opp ynab-kontoer.
Jeg får opp budsjettet når jeg legger in api-nøkkelen, men når jeg skal koble sammen kontoer mellom sbanken og ynab så kommer det ikke noe opp på ynab-delen (sbanken funker).

Er det mulig å få ut noe logger e.l. for å se hva som skjer?

Testet med samme resultat i Firefox og Chrome

**Comment by Wedvich** [comment]
Humm, ser du noe i nettverksloggen? Er det noen kall som feiler? Dette er de kallene du kan forvente å se når det er satt opp når appen laster inn:

![image](https://user-images.githubusercontent.com/1078076/150399560-b28865ae-14e2-491e-b4ec-13a2d2880a63.png)

Da skal det kallet til YNAB sin `/accounts` inneholde budget GUID og liste ut kontoene i det budsjettet. Får du opp det?

**Comment by metasikander** [comment]
Hmm. Jeg får ikke noen feil i nettverksloggen, men det skjer ikke noe mot ynab i det hele tatt.
Jeg testa med å legge inn nøklene på nytt, og der kommuniseres det mot ynab, men ikke når jeg skal sette opp kontoene.
Jeg har også testa med den som du har publisert, og får samme problem der.
Kan det være noe med nøklene jeg bruker?

**Comment by Wedvich** [comment]
Hmm, veldig merkelig 🤔 YNAB sin access token har ikke noe scoping så vidt jeg vet, så så lenge du får lastet inn budsjettene skal den jo være gyldig. Når du er på denne siden og både YNAB og Sbanken er koblet til:

![image](https://user-images.githubusercontent.com/1078076/150668994-6e39132d-2f73-4b35-8d16-a94f38537350.png)

Da skal først disse kallene ha skjedd:

![image](https://user-images.githubusercontent.com/1078076/150669016-26c06a37-44e5-441e-a9c5-853c07d3f4f2.png)

Og i `localStorage` skal du finne disse verdiene:

![image](https://user-images.githubusercontent.com/1078076/150669051-62f5ff4b-c9be-4358-9bfb-776136e5f9f2.png)

Når du da trykker "Gå videre" skal den laste inn kontoer fra både YNAB og Sbanken:

![image](https://user-images.githubusercontent.com/1078076/150669132-a97300d8-826a-40ac-b4fe-dca65c5a83e5.png)

Hvilke av disse tingene er det som ikke skjer?

**Comment by metasikander** [comment]
her er kallene fra den første siden.
![image](https://user-images.githubusercontent.com/2529307/150744700-82d09e85-73d5-4b0b-832c-0f9c67773e80.png)

her er kallene når jeg går videre.
![image](https://user-images.githubusercontent.com/2529307/150745142-719d5d64-e935-46f0-8b43-a160ae751a54.png)

her er local storage. jeg får bare de to.
![image](https://user-images.githubusercontent.com/2529307/150745422-b99433a5-1ee0-4a33-8b84-bddcc1d01233.png)

**Comment by metasikander** [comment]
nå har jeg også testet med "incognito mode" og med en annen server, samme problem.
du kan sjekke mitt oppsett her hvis du vil: https://sbanken-ynab.lhote.me

**Comment by Wedvich** [comment]
Ah ja, det ser ut som om den ikke klarer å sette riktig budsjett. Endrer du på det i dropdownen, eller lar du bare det som er default stå der? Jeg tror kanskje det er buggen her, at den ikke plukker opp default budsjettet etter at de er lastet inn 🤔 

Hva hvis du manuelt henter ut budget ID'en og legger inn i localStorage og så laster siden på nytt?

![image](https://user-images.githubusercontent.com/1078076/150755797-e93e746e-c53b-40e2-a911-e51c57225c6f.png)

```js
localStorage.setItem('ynab:budget', 'whatever den IDen var')
```

**Comment by metasikander** [comment]
okey. jeg har variert mellom å velge i dropdown og la den være. når jeg har trykket på den, så har jeg ikke kunnet gjøre noe annet enn å velge det budsjettet jeg har.

fulgte guiden din nå og det ser ut til å ha fiksa det.
hvor lang tid kan jeg regne med at det vil ta fra det er satt opp til det vises i ynab?
og hvor ofte synkes det?

**Comment by Wedvich** [comment]
Nice 🎉 Skal få fikset den!

Det er ingen auto-sync eller lokal caching av data foreløpig, så hvis du vil oppdatere en konto må du bare refreshe siden. Jeg har også bygget opp appen på nytt fra bunnen av siden den første versjonen var ganske råtten og vanskelig å bygge videre på. Derfor mangler den foreløpig viktigste delen av funksjonaliteten: en knapp for å synce en Sbanken-transaksjon til YNAB 😅 Men skal få lagt den inn i kveld.

**Comment by metasikander** [comment]
Sweet!
Tusen takk for hjelpen!

**Comment by metasikander** [comment]
hei. ikke meningen å mase, men når tror du at du får inn synk-knappen mot ynab?
er det evt. mulig å gjøre det manuelt i browseren?

**Comment by Wedvich** [comment]
Den skal være der nå, men kanskje ikke så god UX... men hvis du holder musen over en Sbanken-transaksjon skal det være en knapp der som oppretter en i YNAB også! Fortsatt mer tweaks som må til (og tydeligvis bedre UX) men it's a start!

**Comment by metasikander** [comment]
ahh. så bra!
ja jeg skjønte ikke det når jeg ikke så det, men da vet jeg at det er der!
