### ISSUE TITLE
Hvorfor tar man ikke med "payee_name" i transaksjonen?

### ISSUE THREAD

**Issue by sveinare** [Wedvich/sbanken-ynab#69]
Tester "sbanken-ynab" og "SbankenToYNAB" litt om hverandre og merker meg følgende:

* De lager duplikate transaksjoner om man bruker dem om hverandre.
* Hvorfor tar du ikke med "payee_name" i transaksjonen?

Dette verktøyet er veldig elegant (selv om jeg ikke helt skjønte at man kunne importere en-og-en transaksjon fra UI første gangen (var litt anonym funksjonalitet). Men ganske frustrerende at mergingen (vurderingen om en transaksjon er i SBanken/YNAB eller begge) ikke er 100%.

**Comment by Wedvich** [comment]
Hey! Min egen erfaring er at navnet jeg får tilbake fra Sbanken sjelden stemmer med det faktiske navnet på payee i YNAB, og det er ikke så enkelt å lage en robust parser som kan trekke ut navnet. Under er et eksempel på det jeg får fra Sbanken sitt API:

```
*XXXX 23.06 NOK 400.00 NO1085 NORMAL OSLO Kurs: 1.0000 
```

I YNAB har jeg en payee som heter `Normal`, men det er ikke noen god måte å trekke ut det navnet fra beskrivelsen uten at jeg manuelt setter opp noen regler selv. Men kanskje det er mulig å la brukere sette opp den mappingen selv, så f.eks. `NO1085 NORMAL OSLO` alltid blir oversatt til `Normal`. Skal se litt nærmere på det!

Mergingen er generelt litt tricky - for eksempel er bokføringsdato i Sbanken gjerne forskjellig fra datoen transaksjonen faktisk ble gjennomført, og jeg ønsker jo den faktiske datoen i YNAB hvis jeg skal gå tilbake og se hvor mye penger jeg brukte på fredag for eksempel. Transaksjoner fra Vipps har også tidligere vært noe dritt å mappe siden de har inneholdt så lite informasjon, men jeg ser at Sbanken nylig har begynt å koble denne informasjonen både i API'et og nettbanken, så det kan fikses 💡  Mergingen vil nok aldri bli 100% før det kommer en førsteparts integrasjon mellom YNAB og Sbanken (så... aldri) men den kan definitivt bli bedre.

Takk for innspill om at den import-funksjonaliteten er litt usynlig, skal prøve å få den bedre frem!

**Comment by sveinare** [comment]
Fra det andre verktøyet jeg brukte (https://github.com/stenjo/SbankenToYNAB, som importerer uten UI), så ble payee utledet på et vis, men det var ofte ikke særlig informativt (hver H&M-filial får f.eks. sin egen Payee, som er unødvendig). Så jeg tenker det er like greit å fylle det ut selv i YNAB.

**Comment by sveinare** [comment]
Ulempen med at vi ikke populerer payee-feltet med noenting, er at da kan vi heller ikke utnytte fuzzy-logikken som ligger i YNAB.  F.eks. at de vanligste stedene (dagligvare-kjeder) kommer inn automatisk. 

Skulle gjerne sett noen form for logikk her - så feltet kan bli populert - og man kan leke seg med "Renaming Rules " i payee-management.

**Comment by Wedvich** [comment]
Takk for linken! Jeg har også merket i det siste at jeg gjerne skulle hatt autoutfylling av payee (med medfølgende auto-kategorisering) så jeg har dette på listen min over ting å se nærmere på 👍
