### ISSUE TITLE
Ønske om valg: Ikke inkluder reserverte transaksjoner

### ISSUE THREAD

**Issue by sveinare** [Wedvich/sbanken-ynab#71]
Når transaksjonen kun er reservert, kan beløpet være midlertidig og det kan hende at det kommer endringer når den blir bokført (litt usikker her). 

Uansett, så pleier jeg ikke å importere dem til YNAB før de faktisk er bokført. 

Så da hadde det vært fint med et filter-valg i toppen som kun viste bokførte transaksjoner.

**Comment by Wedvich** [comment]
Med den siste oppdateringen er det nå sånn by default (kun bokførte transaksjoner vises fra Sbanken) 👍

**Comment by sveinare** [comment]
Det store oppdateringen er helt konge!
