### ISSUE TITLE
Tilby appen som PWA / "install as app" i Chrome

### ISSUE THREAD

**Issue by sveinare** [Wedvich/sbanken-ynab#80]
Hadde vært flott om "sbanken-ynab" kunne installeres som en wbe-app (PWA) og dermed kjøre lokalt som "sin egen app".
Har du erfaring med det?

<img width="181" alt="image" src="https://user-images.githubusercontent.com/181748/209658926-481c841f-b6dc-4ceb-bdbe-ecd21defc249.png">

**Comment by Wedvich** [comment]
Har ikke noe erfaring med det, men det er allerede en service worker involvert så det burde jo i utgangspunktet ikke være noen stor sak å få til. Skal undersøke! 🤔
